config:
  aws:region: us-east-1
  career-presentation:githubOrg: rafaelhueb92
  career-presentation:githubRepo: career-presentation
  career-presentation:githubBranch: master
  career-presentation:priceClass: PriceClass_100
